### ISSUE TITLE
Frontend implementation

### ISSUE THREAD

**Issue by a-shanmugam** [NLP-Challenges/Study-Bot#15]
Implementiert das folgende Requirement: #10 #17 

# Beschreibung / Notizen
Dieser Task handelt sich um sämtliche Frontend Komponenten. 

# Subtasks
- [ ] Chat Interface UI Design
- [ ] Avatar Design (wünschenswert)
- [ ] Animation des Avatars (wünschenswert)
- [ ] Voice (Text-To-Speech) Konzept / Design (Stimmenauswahl) (wünschenswert)
